[package]
name = "mcping-widget"
version = "0.1.0"
authors = ["Cldfire"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
mcping = "0.2"
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
