on:
  push:
    branches:
    - main
  pull_request:

name: Swift CI

jobs:
  Lint:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/mint
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Mint Packages
        uses: actions/cache@v1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Swift Bootstrap
        run: sh swift/scripts/bootstrap.sh

      - name: SwiftLint
        run: mint run swiftlint

      - name: SwiftFormat
        run: mint run swiftformat . --lint

  Test:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/mint
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Mint Packages
        uses: actions/cache@v1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Swift Bootstrap
        run: sh swift/scripts/bootstrap.sh

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cbindgen
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cbindgen

      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: swift/MinecraftStatus.xcodeproj
          scheme: Minecraft Status
          destination: platform=iOS Simulator,name=iPhone 12
          action: test
          # quiet: false
          # use-xcpretty: false
          # hide-shell-script-environment: false

